carcollector/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('cars/', views.cars_index, name='index'),
    path('cars/<int:car_id>/', views.cars_detail, name='detail'),
    path('cars/create/', views.CarCreate.as_view(), name='cars_create'),
    path('cars/<int:pk>/update/', views.CarUpdate.as_view(), name='cars_update'),
    path('cars/<int:pk>/delete/', views.CarDelete.as_view(), name='cars_delete'),
    path('cars/<int:car_id>/add_fueling/', views.add_fueling, name='add_fueling'),
    path('tires/', views.TiresList.as_view(), name='tires_index'),
    path('tires/<int:pk>/', views.TiresDetail.as_view(), name='tires_detail'),
    path('tires/create/', views.TiresCreate.as_view(), name='tires_create'),
    path('tires/<int:pk>/update/', views.TiresUpdate.as_view(), name='tires_update'),
    path('tires/<int:pk>/delete/', views.TiresDelete.as_view(), name='tires_delete'),
    path('cars/<int:car_id>/assoc_tire/<int:tire_id>/', views.assoc_tire, name='assoc_tire'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
# Create your models here.

FUELS = (
    ('A', 'Regular Unleaded' ),
    ('B', 'Premium Unleaded'),
    ('C', 'Supreme Unleaded'),
    ('E', 'Ethanol Fuel')
)

class Tires(models.Model):
    name = models.CharField(max_length=35)
    origin = models.CharField(max_length=35)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('tires_detail', kwargs={'pk': self.id})




class Car(models.Model):
    name = models.CharField(max_length=35)
    manufacturer = models.CharField(max_length=35)
    horsepower = models.IntegerField()
    tires = models.ManyToManyField(Tires)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detail', kwargs={'car_id': self.id})

class Fueling(models.Model):
  date = models.DateField('Date Fueled:')
  fuel = models.CharField(
    'Fuel Types',
    max_length=1,
    choices=FUELS,
    default=FUELS[0][0]
  )
  # create a cat_id column in the db
  car = models.ForeignKey(Car, on_delete=models.CASCADE)

  def __str__(self):
    return f"{self.get_fuel_display()} on {self.date}"

  class Meta:
    ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Fueling

class FuelingForm(ModelForm):
  class Meta:
    model = Fueling
    fields = ['date', 'fuel']

main_app/views.py
# Create your views here.
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Car, Tires
from .forms import FuelingForm
# Add the following import
from django.http import HttpResponse

# # Add the Cat class & list and view function below the imports
# class Car:  # Note that parens are optional if not inheriting from another class
#   def __init__(self, name, manufacturer, horsepower):
#     self.name = name
#     self.manufacturer = manufacturer
#     self.horsepower = horsepower
   

# cars = [
#   Car('Supra', 'Toyota', 600),
#   Car('M3', 'BMW', 580),
#   Car('WRX STI', 'Subaru', 310)
# ]

# Define the home view
def home(request):
  return HttpResponse('<h1>This is the app home page</h1>')

def about(request):
  return render(request, 'about.html')

def cars_index(request):
    cars = Car.objects.all()
    return render(request, 'cars/index.html', {'cars': cars})

def cars_detail(request, car_id):
    car = Car.objects.get(id=car_id)
    id_list = car.tires.all().values_list('id')
    tires_car_doesnt_have = Tires.objects.exclude(id__in=id_list)
    fueling_form = FuelingForm()
    return render(request, 'cars/detail.html', {'car': car, 'fueling_form': fueling_form, 'tires': tires_car_doesnt_have})

def add_fueling(request, car_id):

  form = FuelingForm(request.POST)
  
  if form.is_valid():
    new_fueling = form.save(commit=False)
    new_fueling.car_id = car_id
    new_fueling.save()
  return redirect('detail', car_id=car_id)

class CarCreate(CreateView):
  model = Car
  fields = ['name', 'manufacturer', 'horsepower']

class CarUpdate(UpdateView):
  model = Car
  fields = ['name', 'manufacturer', 'horsepower']

class CarDelete(DeleteView):
  model = Car
  success_url = '/cars/'


class TiresList(ListView):
  model = Tires

class TiresDetail(DetailView):
  model = Tires

class TiresCreate(CreateView):
  model = Tires
  fields = '__all__'

class TiresUpdate(UpdateView):
  model = Tires
  fields = ['name', 'origin']

class TiresDelete(DeleteView):
  model = Tires
  success_url = '/tires/'

def assoc_tire(request, car_id, tire_id):
  # Note that you can pass a toy's id instead of the whole toy object
  Car.objects.get(id=car_id).tires.add(tire_id)
  return redirect('detail', car_id=car_id)

main_app/templates/about.html
{%extends 'base.html'%} {%block content%}

<h1>About the Car Collector</h1>
<hr />
<p>Hire the Car Collector!</p>


{%endblock%}

main_app/templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Car Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="{%url 'home'%}" class="left brand-logo">&nbsp;&nbsp;CarCollector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{%url 'about'%}">About</a></li>
          <li><a href="{% url 'tires_create' %}">Add a Tire Brand</a></li>
          <li><a href="{% url 'tires_index' %}">View All Tire Brands</a></li>
          <li><a href="{% url 'cars_create' %}">Add a Car</a></li>
          <li><a href="{%url 'index'%}">View All My Cars</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2021 Car Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/cars/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Car Details</h1>

<div class="card">
  <div class="card-content">
    <span class="card-title">{{ car.name }}</span>
    <p>Manufacturer: {{ car.manufacturer }}</p>
    <p>Horsepower: {{ car.horsepower }}</p>
  </div>
  <div class="card-action">
    <a href="{% url 'cars_update' car.id %}">Edit</a>
    <a href="{% url 'cars_delete' car.id %}">Delete</a>
  </div>
</div>
</div>
<div class="col s6">
  <form action='{%url 'add_fueling' car.id%}' method="POST">
    {% csrf_token %}
    {{ fueling_form.as_p }}
    <input type="submit" class="btn" value="Add Fueling">
  </form>
  <table class="striped">
    <thead>
      <tr><th>Date</th><th>Fueled</th></tr>
    </thead>
    <tbody>
      {% for fuel in car.fueling_set.all %}
        <tr>
          <td>{{fuel.date}}</td>
          <td>{{fuel.get_fuel_display}}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
</div>

<hr>
<div class="row">
  <div class="col s6">
    <h3>{{ car.name }}'s Tires</h3>
    {% if car.tires.count %}
      {% for tire in car.tires.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              {{ tire.name }} is from {{ tire.origin }}
            </span>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No Tires :(</h5>
    {% endif %}
  </div>
  <div class="col s6">
    <h3>Available Tires</h3>
    {% if tires.count %}
      {% for tire in tires.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              {{ tire.name }} is from {{ tire.origin }}
            </span>
          </div>
          <div class="card-action">
            <form action="{%url 'assoc_tire' car.id tire.id%}" method="POST">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{cat.name}} Already Has All Toys Available</h5>
    {% endif %}
  </div>
</div>
<script>
  const dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });

  const selectEl = document.getElementById('id_fuel');
  M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/cars/index.html
{% extends 'base.html' %} {% block content %}

<h1>Car List</h1>

{% for car in cars %}
<div class="card">
  <a href="{%url 'detail' car.id%}">
    <div class="card-content">
      <span class="card-title">{{ car.name }}</span>
      <p>Manufacturer: {{ car.manufacturer }}</p>
      <p>horsepower: {{ car.horsepower }}</p>
    </div>
  </a>
</div>
{% endfor %} {% endblock %}

main_app/templates/main_app/car_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Car</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' car.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/car_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
<h1>Edit <span class="teal-text">{{car.name}}</span></h1>
{% else %}
<h1>Add Car</h1>
{% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="POST">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/tires_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Tires</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'tires_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/tires_detail.html
{% extends 'base.html' %} {% block content %}

<h1>Tire Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ tires.name }}</span>
        <p>Origin: {{ tires.origin }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'tires_update' tires.id %}">Edit</a>
        <a href="{% url 'tires_delete' tires.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/tires_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Tire</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/tires_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Tires List</h1>

{% for tire in tires_list %}
  <a href="{% url 'tires_detail' tire.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ tire.name }}</span>
            <p>Origin: {{ tire.origin }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}